"""tabla author

Revision ID: d0fb74d865ae
Revises: bbfa702683db
Create Date: 2026-05-28 08:53:16.894284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fb74d865ae'
down_revision: Union[str, Sequence[str], None] = 'bbfa702683db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('songs', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
